import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/homepage/navbar";
import Image from "next/image";
import Footer from "@/components/homepage/Footer";
import { ClientQueryProvider } from "@/providers/clientQueryProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientQueryProvider>
      <body>
        <div className="fixed inset-0 z-[-1]">
          {" "}
          <Image
            src="/heroBg.png" 
            alt="Background Image"
            fill
            style={{ objectFit: "cover" }}
          />
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
      </ClientQueryProvider>
    </html>
  );
}
